/**
 * AncientTongue.AI — Multi-Language Report Translations
 * 7 Languages: zh, en, de, es, ar, th, ms
 * 
 * Translation principles:
 * - TCM terms follow WHO standard nomenclature where possible
 * - Acupoints use international codes + pinyin (e.g., LV3 Taichong)
 * - Classical formulas: pinyin + local language translation
 * - Arabic uses RTL direction flag
 * - German translations reviewed for clinical accuracy
 */

export const translations = {
  "meta": {
    "version": "1.0.0",
    "languages": [
      "zh",
      "en",
      "de",
      "es",
      "ar",
      "th",
      "ms"
    ],
    "languageNames": {
      "zh": "中文",
      "en": "English",
      "de": "Deutsch",
      "es": "Español",
      "ar": "العربية",
      "th": "ไทย",
      "ms": "Bahasa Melayu"
    },
    "flags": {
      "zh": "🇨🇳",
      "en": "🇬🇧",
      "de": "🇩🇪",
      "es": "🇪🇸",
      "ar": "🇸🇦",
      "th": "🇹🇭",
      "ms": "🇲🇾"
    },
    "direction": {
      "zh": "ltr",
      "en": "ltr",
      "de": "ltr",
      "es": "ltr",
      "ar": "rtl",
      "th": "ltr",
      "ms": "ltr"
    }
  },
  "report": {
    "badge": {
      "zh": "PRO+ 深度分析",
      "en": "PRO+ DEEP ANALYSIS",
      "de": "PRO+ TIEFENANALYSE",
      "es": "ANÁLISIS PROFUNDO PRO+",
      "ar": "تحليل عميق PRO+",
      "th": "PRO+ วิเคราะเชิงเชิก",
      "ms": "ANALISIS MENDALAM PRO+"
    },
    "eyebrow": {
      "zh": "辨证分型报告",
      "en": "Pattern Differentiation Report",
      "de": "Syndrom-Differenzierungsbericht",
      "es": "Informe de Diferenciación de Patrones",
      "ar": "تقرير التمييز بين الأنماط",
      "th": "รายงานการแยกกลุ่มอาการ",
      "ms": "Laporan Pembezaan Corak"
    },
    "tongueDorsal": {
      "zh": "舌面观",
      "en": "Dorsal View",
      "de": "Dorsale Ansicht",
      "es": "Vista Dorsal",
      "ar": "المنظر العلوي",
      "th": "มุมมองด้านบน",
      "ms": "Pandangan Dorsal"
    },
    "tongueVentral": {
      "zh": "舌下观",
      "en": "Ventral View",
      "de": "Ventrale Ansicht",
      "es": "Vista Ventral",
      "ar": "المنظر السفلي",
      "th": "มุมมองด้านล่าง",
      "ms": "Pandangan Ventral"
    },
    "tongueImageArea": {
      "zh": "舌象图片区域",
      "en": "Tongue Image Area",
      "de": "Zungenbildbereich",
      "es": "Área de Imagen de la Lengua",
      "ar": "منطقة صورة اللسان",
      "th": "พื้นที่ภาพลิ้น",
      "ms": "Kawasan Imej Lidah"
    },
    "sublingualImageArea": {
      "zh": "舌下图片区域",
      "en": "Sublingual Image Area",
      "de": "Sublingualer Bildbereich",
      "es": "Área de Imagen Sublingual",
      "ar": "منطقة صورة تحت اللسان",
      "th": "พื้นที่ภาพใต้ลิ้น",
      "ms": "Kawasan Imej Sublingual"
    },
    "reportId": {
      "zh": "报告编号",
      "en": "Report ID",
      "de": "Berichts-ID",
      "es": "ID del Informe",
      "ar": "رقم التقرير",
      "th": "รหัสรายงาน",
      "ms": "ID Laporan"
    },
    "generatedByAI": {
      "zh": "内容由AI生成",
      "en": "Generated by AI",
      "de": "KI-generiert",
      "es": "Generado por IA",
      "ar": "أنشئ بواسطة الذكاء الاصطناعي",
      "th": "สร้างโดย AI",
      "ms": "Dijana oleh AI"
    },
    "female": {
      "zh": "女",
      "en": "Female",
      "de": "Weiblich",
      "es": "Femenino",
      "ar": "أنثى",
      "th": "หญิง",
      "ms": "Perempuan"
    },
    "male": {
      "zh": "男",
      "en": "Male",
      "de": "Männlich",
      "es": "Masculino",
      "ar": "ذكر",
      "th": "ชาย",
      "ms": "Lelaki"
    },
    "yearsOld": {
      "zh": "{age}岁",
      "en": "{age} years old",
      "de": "{age} Jahre",
      "es": "{age} años",
      "ar": "{age} سنة",
      "th": "{age} ปี",
      "ms": "{age} tahun"
    },
    "bornYear": {
      "zh": "生于{year}年（农历）",
      "en": "Born {year} (Lunar Calendar)",
      "de": "Geboren {year} (Mondkalender)",
      "es": "Nacido en {year} (Calendario Lunar)",
      "ar": "مولود {year} (التقويم القمري)",
      "th": "เกิดปี {year} (ปฏิทินจันทรคติ)",
      "ms": "Dilahirkan {year} (Kalendar Lunar)"
    }
  },
  "sections": {
    "tongueBody": {
      "eyebrow": {
        "zh": "第一部分",
        "en": "Section I",
        "de": "Abschnitt I",
        "es": "Sección I",
        "ar": "القسم الأول",
        "th": "ส่วนที่ I",
        "ms": "Bahagian I"
      },
      "title": {
        "zh": "舌面精细分析",
        "en": "Tongue Body Analysis",
        "de": "Zungenkörperanalyse",
        "es": "Análisis del Cuerpo de la Lengua",
        "ar": "تحليل جسم اللسان",
        "th": "การวิเคราะตัวลิ้น",
        "ms": "Analisis Badan Lidah"
      }
    },
    "sublingual": {
      "eyebrow": {
        "zh": "第二部分",
        "en": "Section II",
        "de": "Abschnitt II",
        "es": "Sección II",
        "ar": "القسم الثاني",
        "th": "ส่วนที่ II",
        "ms": "Bahagian II"
      },
      "title": {
        "zh": "舌下精细分析",
        "en": "Sublingual Analysis",
        "de": "Sublinguale Analyse",
        "es": "Análisis Sublingual",
        "ar": "التحليل تحت اللسان",
        "th": "การวิเคราะใต้ลิ้น",
        "ms": "Analisis Sublingual"
      }
    },
    "crossValidation": {
      "eyebrow": {
        "zh": "第三部分",
        "en": "Section III",
        "de": "Abschnitt III",
        "es": "Sección III",
        "ar": "القسم الثالث",
        "th": "ส่วนที่ III",
        "ms": "Bahagian III"
      },
      "title": {
        "zh": "舌上+舌下互证",
        "en": "Cross-Validation Findings",
        "de": "Kreuzvalidierung der Befunde",
        "es": "Hallazgos de Validación Cruzada",
        "ar": "نتائج التحقق المتبادل",
        "th": "ผลการตรวจสอยข้าม",
        "ms": "Penemuan Sah Silang"
      }
    },
    "pathogenesis": {
      "eyebrow": {
        "zh": "第四部分",
        "en": "Section IV",
        "de": "Abschnitt IV",
        "es": "Sección IV",
        "ar": "القسم الرابع",
        "th": "ส่วนที่ IV",
        "ms": "Bahagian IV"
      },
      "title": {
        "zh": "病机整合",
        "en": "Pathogenesis Integration",
        "de": "Pathogenese-Integration",
        "es": "Integración de la Patogénesis",
        "ar": "تكامل آلية المرض",
        "th": "การบูรณากลเกลกกเกิดโรค",
        "ms": "Integrasi Patogenesis"
      }
    },
    "symptomPredictions": {
      "eyebrow": {
        "zh": "第五部分",
        "en": "Section V",
        "de": "Abschnitt V",
        "es": "Sección V",
        "ar": "القسم الخامس",
        "th": "ส่วนที่ V",
        "ms": "Bahagian V"
      },
      "title": {
        "zh": "症状预判",
        "en": "Symptom Predictions",
        "de": "Symptomvorhersagen",
        "es": "Predicciones de Síntomas",
        "ar": "توقعات الأعراض",
        "th": "การทำนายอาการ",
        "ms": "Ramalan Simptom"
      }
    },
    "redFlags": {
      "eyebrow": {
        "zh": "第六部分",
        "en": "Section VI",
        "de": "Abschnitt VI",
        "es": "Sección VI",
        "ar": "القسم السادس",
        "th": "ส่วนที่ VI",
        "ms": "Bahagian VI"
      },
      "title": {
        "zh": "红线检查",
        "en": "Red Flag Screening",
        "de": "Red-Flag-Screening",
        "es": "Screening de Signos de Alarma",
        "ar": "فحص العلامات الحمراء",
        "th": "การคัดกรองสัญญาณเตือน",
        "ms": "Saringan Bendera Merah"
      }
    },
    "externalTreatment": {
      "eyebrow": {
        "zh": "第七部分",
        "en": "Section VII",
        "de": "Abschnitt VII",
        "es": "Sección VII",
        "ar": "القسم السابع",
        "th": "ส่วนที่ VII",
        "ms": "Bahagian VII"
      },
      "title": {
        "zh": "外治方案",
        "en": "External Treatment Protocols",
        "de": "Externe Behandlungsprotokolle",
        "es": "Protocolos de Tratamiento Externo",
        "ar": "بروتوكولات العلاج الخارجي",
        "th": "โปรโตคอลการรักษาภายนอก",
        "ms": "Protokol Rawatan Luaran"
      }
    },
    "foodTherapy": {
      "eyebrow": {
        "zh": "第八部分",
        "en": "Section VIII",
        "de": "Abschnitt VIII",
        "es": "Sección VIII",
        "ar": "القسم الثامن",
        "th": "ส่วนที่ VIII",
        "ms": "Bahagian VIII"
      },
      "title": {
        "zh": "食疗推荐",
        "en": "Food Therapy Recommendations",
        "de": "Ernährungstherapeutische Empfehlungen",
        "es": "Recomendaciones de Dietoterapia",
        "ar": "توصيات العلاج الغذائي",
        "th": "คำแนะนำการบำบัด้วยอาหาร",
        "ms": "Cadangan Terapi Makanan"
      }
    },
    "classicalFormula": {
      "eyebrow": {
        "zh": "第九部分",
        "en": "Section IX",
        "de": "Abschnitt IX",
        "es": "Sección IX",
        "ar": "القسم التاسع",
        "th": "ส่วนที่ IX",
        "ms": "Bahagian IX"
      },
      "title": {
        "zh": "经方参考方向",
        "en": "Classical Formula Reference",
        "de": "Klassische Rezepturreferenz",
        "es": "Referencia de Fórmulas Clásicas",
        "ar": "مرجع الوصفات الكلاسيكية",
        "th": "อ้างอิงตำรับยาโบราณบูราณ",
        "ms": "Rujukan Formula Klasik"
      }
    },
    "dietaryRules": {
      "eyebrow": {
        "zh": "第十部分",
        "en": "Section X",
        "de": "Abschnitt X",
        "es": "Sección X",
        "ar": "القسم العاشر",
        "th": "ส่วนที่ X",
        "ms": "Bahagian X"
      },
      "title": {
        "zh": "饮食铁律",
        "en": "Dietary Rules",
        "de": "Ernährungsregeln",
        "es": "Reglas Dietéticas",
        "ar": "قواعد النظام الغذائي",
        "th": "กฎระเบียบด้านอาหาร",
        "ms": "Peraturan Pemakanan"
      }
    },
    "keyIndicators": {
      "eyebrow": {
        "zh": "第十一部分",
        "en": "Section XI",
        "de": "Abschnitt XI",
        "es": "Sección XI",
        "ar": "القسم الحادي عشر",
        "th": "ส่วนที่ XI",
        "ms": "Bahagian XI"
      },
      "title": {
        "zh": "核心指标",
        "en": "Key Recovery Indicators",
        "de": "Wesentliche Erholungsindikatoren",
        "es": "Indicadores Clave de Recuperación",
        "ar": "مؤشرات التعافي الرئيسية",
        "th": "ตัวบงชี้การฟื้นตัวหลัก",
        "ms": "Penunjuk Pemulihan Utama"
      }
    },
    "healingCrisis": {
      "eyebrow": {
        "zh": "第十二部分",
        "en": "Section XII",
        "de": "Abschnitt XII",
        "es": "Sección XII",
        "ar": "القسم الثاني عشر",
        "th": "ส่วนที่ XII",
        "ms": "Bahagian XII"
      },
      "title": {
        "zh": "排病反应须知",
        "en": "Healing Crisis Notice",
        "de": "Hinweis zur Erstverschlimmerung",
        "es": "Aviso de Crisis Curativa",
        "ar": "إشعار أزمة الشفاء",
        "th": "แจ้งเรื่องปฏิกิริยาการบำบัด",
        "ms": "Notis Krisis Penyembuhan"
      }
    }
  },
  "tcm": {
    "patterns": {
      "yangStagnationBloodStasis": {
        "zh": "阳郁血瘀",
        "en": "Stagnated Yang with Blood Stasis",
        "de": "Yang-Stagnation mit Blut-Stase",
        "es": "Yang Estancado con Estasis de Sangre",
        "ar": "ركود اليانغ مع ركود الدم",
        "th": "หยางติดขัดกับเลือดค้าง",
        "ms": "Yang Tertegun dengan Stasis Darah"
      },
      "liverQiStagnation": {
        "zh": "肝气郁结",
        "en": "Liver Qi Stagnation",
        "de": "Leber-Qi-Stagnation",
        "es": "Estancamiento del Qi del Hígado",
        "ar": "ركود تشي الكبد",
        "th": "ชี่ตับติดขัด",
        "ms": "Stagnasi Qi Hati"
      },
      "qiStagnationBloodStasis": {
        "zh": "气滞血瘀",
        "en": "Qi Stagnation with Blood Stasis",
        "de": "Qi-Stagnation mit Blut-Stase",
        "es": "Estancamiento de Qi con Estasis de Sangre",
        "ar": "ركود التشي مع ركود الدم",
        "th": "ชี่ติดขัดกับเลือดค้าง",
        "ms": "Stagnasi Qi dengan Stasis Darah"
      },
      "spleenTransportDysfunction": {
        "zh": "脾失健运",
        "en": "Spleen Transport Dysfunction",
        "de": "Milz-Transport-Dysfunktion",
        "es": "Disfunción del Transporte del Bazo",
        "ar": "خلل وظيفة نقل الطحال",
        "th": "การทำงานของม้ามผิดปกติ",
        "ms": "Disfungsi Pengangkutan Limpa"
      },
      "liverConstraintYangSuppression": {
        "zh": "肝郁阳遏",
        "en": "Liver Constraint with Yang Suppression",
        "de": "Leber-Obstruktion mit Yang-Unterdrückung",
        "es": "Obstrucción Hepática con Supresión de Yang",
        "ar": "احتباس الكبد مع كبت اليانغ",
        "th": "ตับติดขัดกับหยางถูกกด",
        "ms": "Kekangan Hati dengan Penindasan Yang"
      },
      "heartQiInsufficiency": {
        "zh": "心气不足",
        "en": "Heart Qi Insufficiency",
        "de": "Herz-Qi-Mangel",
        "es": "Insuficiencia del Qi del Corazón",
        "ar": "قصور تشي القلب",
        "th": "ชี่หัวใจไม่เพียงพอ",
        "ms": "Kekurangan Qi Jantung"
      },
      "heartBloodStasis": {
        "zh": "心血瘀阻",
        "en": "Heart Blood Stasis",
        "de": "Herz-Blut-Stase",
        "es": "Estasis de Sangre del Corazón",
        "ar": "ركود دم القلب",
        "th": "เลือดค้างในหัวใจ",
        "ms": "Stasis Darah Jantung"
      },
      "kidneyYangWeakness": {
        "zh": "肾阳推动力弱",
        "en": "Kidney Yang Propulsion Weakness",
        "de": "Nieren-Yang-Antriebsschwäche",
        "es": "Debilidad de Impulso del Yang Renal",
        "ar": "ضعف قوة دفع يانغ الكلى",
        "th": "หยางไตขับเคลื่อนอ่อน",
        "ms": "Kelemahan Daya Dorong Yang Ginjal"
      },
      "coldDampnessRetention": {
        "zh": "寒湿内停",
        "en": "Cold-Dampness Retention",
        "de": "Kälte-Feuchtigkeit-Retention",
        "es": "Retención de Frío-Humedad",
        "ar": "احتباس البرودة والرطوبة",
        "th": "ความเย็น-ชื้นค้าง",
        "ms": "Kekal Sejuk-Lembap"
      },
      "heartSpleenQiBloodDeficiency": {
        "zh": "心脾气血不足",
        "en": "Heart-Spleen Qi-Blood Deficiency",
        "de": "Herz-Milz-Qi-Blut-Mangel",
        "es": "Deficiencia de Qi-Sangre Corazón-Bazo",
        "ar": "نقص تشي-دم القلب والطحال",
        "th": "ชี่-เลือดหัวใจ-ม้ามไม่พอ",
        "ms": "Kekurangan Qi-Darah Jantung-Limpa"
      }
    },
    "sixStages": {
      "jueyin": {
        "zh": "厥阴",
        "en": "Jueyin",
        "de": "Jueyin",
        "es": "Jueyin",
        "ar": "جويين",
        "th": "จวีอิน",
        "ms": "Jueyin"
      },
      "shaoyang": {
        "zh": "少阳",
        "en": "Shaoyang",
        "de": "Shaoyang",
        "es": "Shaoyang",
        "ar": "شاويانغ",
        "th": "เส้าหยาง",
        "ms": "Shaoyang"
      },
      "taiyang": {
        "zh": "太阳",
        "en": "Taiyang",
        "de": "Taiyang",
        "es": "Taiyang",
        "ar": "تاييانغ",
        "th": "ไท่หยาง",
        "ms": "Taiyang"
      },
      "yangming": {
        "zh": "阳明",
        "en": "Yangming",
        "de": "Yangming",
        "es": "Yangming",
        "ar": "يانغ مينغ",
        "th": "หยางหมิง",
        "ms": "Yangming"
      },
      "taiyin": {
        "zh": "太阴",
        "en": "Taiyin",
        "de": "Taiyin",
        "es": "Taiyin",
        "ar": "تايين",
        "th": "ไท่อิน",
        "ms": "Taiyin"
      },
      "shaoyin": {
        "zh": "少阴",
        "en": "Shaoyin",
        "de": "Shaoyin",
        "es": "Shaoyin",
        "ar": "شاوين",
        "th": "เส้าอิน",
        "ms": "Shaoyin"
      }
    },
    "tongueTerms": {
      "narrowConstricted": {
        "zh": "偏窄而紧束",
        "en": "Narrow and constricted",
        "de": "Schmal und zusammengezogen",
        "es": "Estrecha y contraída",
        "ar": "ضيقة ومنقبضة",
        "th": "แคบและหดตัว",
        "ms": "Sempit dan terkekang"
      },
      "darkDull": {
        "zh": "整体偏暗淡",
        "en": "Darkened and dull",
        "de": "Verdunkelt und matt",
        "es": "Oscura y opaca",
        "ar": "داكنة وباهتة",
        "th": "คล้ำและหมอง",
        "ms": "Gelap dan kusam"
      },
      "bluishPurpleEdges": {
        "zh": "舌边偏青紫",
        "en": "Bluish-purple at edges",
        "de": "Bläulich-violett an den Rändern",
        "es": "Azul-púrpura en bordes",
        "ar": "أزرق-أرجواني عند الحواف",
        "th": "สีม่วงน้ำเงินที่ขอบ",
        "ms": "Biru-ungu di tepi"
      },
      "stasisSpotsTip": {
        "zh": "舌尖散在淤点",
        "en": "Scattered stasis spots at tip",
        "de": "Verstreute Stase-Punkte an der Spitze",
        "es": "Manchas de estasis dispersas en punta",
        "ar": "بقع ركود متناثرة عند الطرف",
        "th": "จุดเลือดค้างกระจายที่ปลาย",
        "ms": "Titik stasis bertaburan di hujung"
      },
      "thinWhiteDryCoat": {
        "zh": "薄白偏干苔",
        "en": "Thin white, slightly dry coat",
        "de": "Dünner weißer, leicht trockener Belag",
        "es": "Saburra delgada blanca ligeramente seca",
        "ar": "طبقة رقيقة بيضاء جافة قليلاً",
        "th": "ฝ้าบางขาวแห้งเล็กน้อย",
        "ms": "Lapisan nipis putih sedikit kering"
      },
      "mildTeethMarks": {
        "zh": "舌边轻度齿痕",
        "en": "Mild teeth marks on edges",
        "de": "Leichte Zahnabdrücke an den Rändern",
        "es": "Marcas dentarias leves en los bordes",
        "ar": "آثار أسنان خفيفة على الحواف",
        "th": "รอยฟันเล็กน้อยที่ขอบ",
        "ms": "Kesan gigi ringan di tepi"
      },
      "notSwollen": {
        "zh": "不胖大，偏瘦薄",
        "en": "Not swollen; tends thin and lean",
        "de": "Nicht geschwollen; eher dünn",
        "es": "No inflamada; tiende a delgada",
        "ar": "غير منتفخة؛ تميل للنحافة",
        "th": "ไม่บวม ค่อนข้างบาง",
        "ms": "Tidak bengkak; cenderung nipis"
      }
    },
    "tongueZones": {
      "tip": {
        "zh": "舌尖（心/肺）",
        "en": "Tip (Heart/Lung)",
        "de": "Spitze (Herz/Lunge)",
        "es": "Punta (Corazón/Pulmón)",
        "ar": "الطرف (القلب/الرئة)",
        "th": "ปลายลิ้น (หัวใจ/ปอด)",
        "ms": "Hujung (Jantung/Paru-paru)"
      },
      "center": {
        "zh": "舌中（脾/胃）",
        "en": "Center (Spleen/Stomach)",
        "de": "Mitte (Milz/Magen)",
        "es": "Centro (Bazo/Estómago)",
        "ar": "الوسط (الطحال/المعدة)",
        "th": "ตรงกลาง (ม้าม/กระเพาะ)",
        "ms": "Tengah (Limpa/Perut)"
      },
      "root": {
        "zh": "舌根（肾/下焦）",
        "en": "Root (Kidney/Lower Jiao)",
        "de": "Wurzel (Niere/Unterer Jiao)",
        "es": "Raíz (Riñón/Jiao Inferior)",
        "ar": "الجذر (الكلى/المحرر السفلي)",
        "th": "รากลิ้น (ไต/ซานเจียวล่าง)",
        "ms": "Akar (Ginjal/Jiao Bawah)"
      },
      "edges": {
        "zh": "舌边（肝/胆）",
        "en": "Edges (Liver/Gallbladder)",
        "de": "Ränder (Leber/Gallenblase)",
        "es": "Bordes (Hígado/Vesícula)",
        "ar": "الحواف (الكبد/المرارة)",
        "th": "ขอบลิ้น (ตับ/ถุงน้ำดี)",
        "ms": "Tepi (Hati/Pundi Hempedu)"
      }
    },
    "acupoints": {
      "LV3": {
        "code": "LV3",
        "pinyin": "Taichong",
        "zh": "太冲",
        "en": "Great Surge",
        "de": "Großer Sturm",
        "es": "Gran Oleada",
        "ar": "الاندفاع الكبير",
        "th": "ไถ่ชง",
        "ms": "Gelombang Agung"
      },
      "SP10": {
        "code": "SP10",
        "pinyin": "Xuehai",
        "zh": "血海",
        "en": "Sea of Blood",
        "de": "Meer des Blutes",
        "es": "Mar de Sangre",
        "ar": "بحر الدم",
        "th": "เซี่ยไห่",
        "ms": "Lautan Darah"
      },
      "CV4": {
        "code": "CV4",
        "pinyin": "Guanyuan",
        "zh": "关元",
        "en": "Gate of the Source",
        "de": "Tor der Quelle",
        "es": "Puerta del Origen",
        "ar": "بوابة المصدر",
        "th": "กวนหยวน",
        "ms": "Gerbang Sumber"
      },
      "LI4": {
        "code": "LI4",
        "pinyin": "Hegu",
        "zh": "合谷",
        "en": "Joining Valley",
        "de": "Tal der Vereinigung",
        "es": "Valle de Unión",
        "ar": "وادي الالتقاء",
        "th": "เหอกู่",
        "ms": "Lembah Pertemuan"
      },
      "SP6": {
        "code": "SP6",
        "pinyin": "Sanyinjiao",
        "zh": "三阴交",
        "en": "Three Yin Intersection",
        "de": "Kreuzung der drei Yin",
        "es": "Intersección de los Tres Yin",
        "ar": "تقاطع الين الثلاثة",
        "th": "ซานอินเจียว",
        "ms": "Persimpangan Tiga Yin"
      },
      "BL18": {
        "code": "BL18",
        "pinyin": "Ganshu",
        "zh": "肝俞",
        "en": "Liver Shu",
        "de": "Leber-Shu",
        "es": "Shu del Hígado",
        "ar": "شو الكبد",
        "th": "กานซู",
        "ms": "Shu Hati"
      },
      "BL20": {
        "code": "BL20",
        "pinyin": "Pishu",
        "zh": "脾俞",
        "en": "Spleen Shu",
        "de": "Milz-Shu",
        "es": "Shu del Bazo",
        "ar": "شو الطحال",
        "th": "ผีซู",
        "ms": "Shu Limpa"
      },
      "BL23": {
        "code": "BL23",
        "pinyin": "Shenshu",
        "zh": "肾俞",
        "en": "Kidney Shu",
        "de": "Nieren-Shu",
        "es": "Shu del Riñón",
        "ar": "شو الكلى",
        "th": "เซินซู",
        "ms": "Shu Ginjal"
      }
    },
    "formulas": {
      "siNiSan": {
        "pinyin": "Sì Nì Sǎn",
        "zh": "四逆散",
        "zhSource": "《伤寒论》",
        "en": "Four Counterflow Powder",
        "enSource": "Shang Han Lun — Zhang Zhongjing",
        "de": "Vier-Umkehr-Pulver",
        "deSource": "Shang Han Lun — Zhang Zhongjing",
        "es": "Polvo de los Cuatro Reflujos",
        "esSource": "Shang Han Lun — Zhang Zhongjing",
        "ar": "مسحوق الارتداد الرباعي",
        "arSource": "شانغ هان لون — تشانغ تشونغ جينغ",
        "th": "ซื่อหนี散去",
        "thSource": "ซางหานลุ่น — จาง จ้งจิ้ง",
        "ms": "Serbuk Empat Aliran Balik",
        "msSource": "Shang Han Lun — Zhang Zhongjing"
      },
      "guiZhiFuLingWan": {
        "pinyin": "Guì Zhī Fú Líng Wán",
        "zh": "桂枝茯苓丸",
        "zhSource": "《金匮要略》",
        "en": "Cinnamon & Poria Pill",
        "enSource": "Jin Gui Yao Lue — Zhang Zhongjing",
        "de": "Zimt-Poria-Pille",
        "deSource": "Jin Gui Yao Lue — Zhang Zhongjing",
        "es": "Píldora de Canela y Poria",
        "esSource": "Jin Gui Yao Lue — Zhang Zhongjing",
        "ar": "حبوب القرفة والبوريا",
        "arSource": "جين غوي ياو لويه — تشانغ تشونغ جينغ",
        "th": "กุ้ยจือฝูหลิงหวัน",
        "thSource": "จินกุ้ยเหยาลู่เย่ — จาง จ้งจิ้ง",
        "ms": "Pil Kayu Manis & Poria",
        "msSource": "Jin Gui Yao Lue — Zhang Zhongjing"
      },
      "dangGuiSiNiTang": {
        "pinyin": "Dāng Guī Sì Nì Tāng",
        "zh": "当归四逆汤",
        "zhSource": "《伤寒论》",
        "en": "Angelica Four Counterflow Decoction",
        "enSource": "Shang Han Lun — Zhang Zhongjing",
        "de": "Angelika-Vier-Umkehr-Abkochung",
        "deSource": "Shang Han Lun — Zhang Zhongjing",
        "es": "Decocción de Angélica y Cuatro Reflujos",
        "esSource": "Shang Han Lun — Zhang Zhongjing",
        "ar": "مرقوق الأنجليكا والارتداد الرباعي",
        "arSource": "شانغ هان لون — تشانغ تشونغ جينغ",
        "th": "ตังกุยซื่อหนีทัง",
        "thSource": "ซางหานลุ่น — จาง จ้งจิ้ง",
        "ms": "Rebusan Angelika Empat Aliran Balik",
        "msSource": "Shang Han Lun — Zhang Zhongjing"
      }
    },
    "jiao": {
      "upper": {
        "zh": "上焦",
        "en": "Upper Jiao",
        "de": "Oberer Jiao",
        "es": "Jiao Superior",
        "ar": "المحرر العلوي",
        "th": "ซานเจียวบน",
        "ms": "Jiao Atas"
      },
      "middle": {
        "zh": "中焦",
        "en": "Middle Jiao",
        "de": "Mittlerer Jiao",
        "es": "Jiao Medio",
        "ar": "المحرر الأوسط",
        "th": "ซานเจียวกลาง",
        "ms": "Jiao Tengah"
      },
      "lower": {
        "zh": "下焦",
        "en": "Lower Jiao",
        "de": "Unterer Jiao",
        "es": "Jiao Inferior",
        "ar": "المحرر السفلي",
        "th": "ซานเจียวล่าง",
        "ms": "Jiao Bawah"
      }
    },
    "deficiencyExcess": {
      "deficiency": {
        "zh": "虚",
        "en": "Deficiency",
        "de": "Mangel",
        "es": "Deficiencia",
        "ar": "نقص",
        "th": "พร่อง",
        "ms": "Kekurangan"
      },
      "excess": {
        "zh": "实",
        "en": "Excess",
        "de": "Fülle",
        "es": "Exceso",
        "ar": "فائض",
        "th": "เกิน",
        "ms": "Kelebihan"
      }
    }
  },
  "treatment": {
    "guaSha": {
      "zh": "刮痧",
      "en": "Gua Sha (Scraping Therapy)",
      "de": "Gua Sha (Schabetherapie)",
      "es": "Gua Sha (Terapia de Raspado)",
      "ar": "غوا شا (العلاج بالكشط)",
      "th": "กัวซา (การรักษาด้วยการขูด)",
      "ms": "Gua Sha (Terapi Mengikis)"
    },
    "moxibustion": {
      "zh": "艾灸",
      "en": "Moxibustion",
      "de": "Moxibustion",
      "es": "Moxibustión",
      "ar": "الكَيّ بالأعشاب",
      "th": "โมกซิบัสชัน",
      "ms": "Moksibusi"
    },
    "exercisePrescription": {
      "zh": "运动处方",
      "en": "Exercise Prescription",
      "de": "Bewegungsrezept",
      "es": "Prescripción de Ejercicio",
      "ar": "وصفة التمارين",
      "th": "ใบสั่งการออกกำลังกาย",
      "ms": "Presripsi Senaman"
    },
    "dailyAcupressure": {
      "zh": "日常保健穴位",
      "en": "Daily Acupressure",
      "de": "Tägliche Akupressur",
      "es": "Acupresión Diaria",
      "ar": "الضغط اليومي",
      "th": "การกดจุดประจำวัน",
      "ms": "Akupresur Harian"
    },
    "contraindications": {
      "zh": "禁忌事项",
      "en": "Contraindications",
      "de": "Kontraindikationen",
      "es": "Contraindicaciones",
      "ar": "موانع",
      "th": "ข้อห้าม",
      "ms": "Kontraindikasi"
    }
  },
  "foodTherapy": {
    "sugarRecommended": {
      "zh": "宜用糖类",
      "en": "Recommended",
      "de": "Empfohlen",
      "es": "Recomendado",
      "ar": "موصى به",
      "th": "แนะนำ",
      "ms": "Disyorkan"
    },
    "sugarAvoid": {
      "zh": "忌用糖类",
      "en": "Avoid",
      "de": "Vermeiden",
      "es": "Evitar",
      "ar": "تجنب",
      "th": "ควรหลีกเลี่ยง",
      "ms": "Elakkan"
    },
    "sugarGoodText": {
      "zh": "红糖、黑糖（温经活血）",
      "en": "Brown sugar, black sugar, raw cane sugar — these warm the Middle Jiao and complement blood-nourishing recipes.",
      "de": "Brauner Zucker, schwarzer Zucker, roher Rohrzucker — diese wärmen den Mittleren Jiao und ergänzen blutnährende Rezepte.",
      "es": "Azúcar moreno, azúcar negro, azúcar de caña sin refinar — calientan el Jiao Medio y complementan recetas nutritivas.",
      "ar": "السكر البني، السكر الأسود، سكر القصب الخام — تدفئ المحرر الأوسط وتكمل وصفات تغذية الدم.",
      "th": "น้ำตาลทรายแดง น้ำตาลดำ น้ำตาลอ้อยดิบ — ช่วยอุ่นซานเจียวกลางและเสริมสูตรบำรุงเลือด",
      "ms": "Gula perang, gula hitam, gula tebu mentah — memanaskan Jiao Tengah."
    },
    "sugarBadText": {
      "zh": "白砂糖、冰糖（助湿碍脾）",
      "en": "White sugar, rock sugar — these are cooling in nature and may counteract the warming intent of the recipes.",
      "de": "Weißer Zucker, Kandiszucker — diese sind kühlender Natur und können die wärmende Absicht der Rezepte beeinträchtigen.",
      "es": "Azúcar blanco, azúcar de roca — son de naturaleza refrescante y pueden contrarrestar el efecto calentador.",
      "ar": "السكر الأبيض، سكر الصخور — ذات طبيعة باردة وقد تبطل التأثير التدفيري.",
      "th": "น้ำตาลทรายขาว น้ำตาลกรวด — มีฤทธิ์เย็นอาจต้านผลอุ่นของสูตร",
      "ms": "Gula putih, gula batu — bersifat menyejukkan dan menghalang kesan pemanasan."
    }
  },
  "dietaryRules": {
    "avoidColdRaw": {
      "title": {
        "zh": "绝对忌生冷",
        "en": "Absolutely Avoid Cold & Raw Foods",
        "de": "Kalte und rohe Speisen strikt meiden",
        "es": "Evitar Alimentos Fríos y Crudos",
        "ar": "تجنب الأطعمة الباردة والنيئة",
        "th": "งดเด็ดขาด: อาหารเย็นและดิบ",
        "ms": "Elak Mutlak Makanan Sejuk & Mentah"
      },
      "detail": {
        "zh": "冰水、冰淇淋、生鱼片、凉拌菜、寒性水果（西瓜、梨、猕猴桃）均忌。生冷伤脾阳，加重阳郁。",
        "en": "Iced beverages, raw salads, sashimi, cold fruits. These directly damage the Spleen Yang and worsen cold-dampness.",
        "de": "Eisgetränke, rohe Salate, Sashimi, kalte Früchte. Diese schädigen direkt das Milz-Yang und verschlimmern Kälte-Feuchtigkeit.",
        "es": "Bebidas heladas, ensaladas crudas, sashimi, frutas frías. Dañan directamente el Yang del Bazo.",
        "ar": "المشروبات المثلجة والسلطات النيئة والساشيمي والفواكه الباردة. تضر يانغ الطحال مباشرة.",
        "th": "น้ำแข็ง สลัดดิบ ซาชิมิ ผลไม้เย็น ทำลายหยางม้ามโดยตรง",
        "ms": "Minuman berais, salad mentah, sashimi, buah sejuk. Merusakkan Yang Limpa."
      }
    },
    "avoidAlcohol": {
      "title": {
        "zh": "戒酒或严格限酒",
        "en": "Avoid or Strictly Limit Alcohol",
        "de": "Alkohol meiden oder strikt begrenzen",
        "es": "Evitar o Limitar el Alcohol",
        "ar": "تجنب الكحول",
        "th": "งดหรือจำกัดแอลกอฮอล์",
        "ms": "Elak atau Hadkan Alkohol"
      },
      "detail": {
        "zh": "酒虽性温但助湿热，肝郁者饮酒易化火动血。如必须饮，仅限少量黄酒。",
        "en": "Alcohol generates damp-heat and burdens the Liver. Limit to small amounts of warm rice wine only.",
        "de": "Alkohol erzeugt Feuchtigkeits-Hitze und belastet die Leber. Nur kleine Mengen warmen Reisweins.",
        "es": "El alcohol genera humedad-calor y sobrecarga el Hígado. Solo pequeñas cantidades de vino de arroz tibio.",
        "ar": "يولد الكحول رطوبة-حرارة ويزيد عبء الكبد. فقط كميات صغيرة من نبيذ الأرز الدافئ.",
        "th": "แอลกอฮอล์ก่อชื้น-ร้อน เพิ่มภาระตับ จำกัดเพียงเหล้าเหลืองอุ่นเล็กน้อย",
        "ms": "Alkohol menjana lembap-panas dan membebankan hati. Hanya arak beras hangat dalam jumlah kecil."
      }
    },
    "avoidSpicy": {
      "title": {
        "zh": "忌辛辣燥烈",
        "en": "Avoid Spicy & Drying Foods",
        "de": "Scharfe und trocknende Speisen meiden",
        "es": "Evitar Alimentos Picantes y Secantes",
        "ar": "تجنب الأطعمة الحارة",
        "th": "งดอาหารเผ็ดและร้อนแห้ง",
        "ms": "Elakkan Makanan Pedas & Kering"
      },
      "detail": {
        "zh": "辣椒、花椒、胡椒等大辛大热之物暂忌。阳郁有化热趋势，过用辛燥反伤阴血。",
        "en": "Excessive chili, deep-fried foods, pungent spices deplete Yin fluids and may exacerbate dryness.",
        "de": "Übermäßiger Chili, Frittiertes, scharfe Gewürze erschöpfen Yin-Flüssigkeiten und verschlimmern Trockenheit.",
        "es": "El exceso de chile, frituras y especias pungentes agotan líquidos Yin y exacerban la sequedad.",
        "ar": "الإفراط في الفلفل والمقليات والتوابل الحارة تستنفد سوائل الين وتزيد الجفاف.",
        "th": "พริกมากเกินไป ของทอด เครื่องเทศเผ็ด ทำลายสารน้ำอินและเพิ่มแนวโน้มแห้ง",
        "ms": "Cili berlebihan, makanan goreng, rempah pedas menghabiskan cecair Yin."
      }
    },
    "dinnerEarly": {
      "title": {
        "zh": "晚餐七分饱·7点前",
        "en": "Dinner at 70% Fullness, Before 7 PM",
        "de": "Abendessen zu 70% Sättigung, vor 19 Uhr",
        "es": "Cena al 70%, Antes de las 19h",
        "ar": "عشاء 70% شبع قبل 7 مساءً",
        "th": "มื้อเย็นอิ่ม 70% ก่อน 1 ทุ่ม",
        "ms": "Makan Malam 70% Kenyang, Sebelum 7 Malam"
      },
      "detail": {
        "zh": "晚饭后脾胃运化减弱，过饱加重中焦负担，影响睡眠和阳气潜藏。",
        "en": "Overeating at night impairs Spleen transport and generates food stagnation. Early light dinners support Yang-collecting rhythm.",
        "de": "Übermäßiges Abendessen beeinträchtigt die Milz-Transportfunktion. Frühe, leichte Abendessen unterstützen den Yang-Sammelrhythmus.",
        "es": "Comer en exceso por la noche perjudica el transporte del Bazo. Cenas tempranas y ligeras apoyan el ritmo de recogida de Yang.",
        "ar": "الإفراط ليلاً يضعف نقل الطحال. العشاء المبكر الخفيف يدعم إيقاع جمع اليانغ.",
        "th": "กินมากเกินไปตอนกลางคืนทำลายการขนส่งม้าม มื้อเย็นเบาๆและเร็วช่วยเก็บหยาง",
        "ms": "Makan berlebihan pada waktu malam mengganggu pengangkutan Limpa. Makan malam awal ringan menyokong irama pengumpulan Yang."
      }
    },
    "limitCoffee": {
      "title": {
        "zh": "咖啡限1杯·上午饮",
        "en": "Limit Coffee to 1 Cup, Morning Only",
        "de": "Kaffee auf 1 Tasse, nur morgens",
        "es": "Café: 1 Taza, Solo Mañana",
        "ar": "قهوة: كوب 1 صباحاً فقط",
        "th": "กาแฟ: 1 แก้ว เฉพาะเช้า",
        "ms": "Kopi: 1 Cawan, Pagi Sahaja"
      },
      "detail": {
        "zh": "少量咖啡可助阳提神，但过量耗伤阴血、加重失眠。下午后禁饮。",
        "en": "Coffee is bitter-warming. In excess it depletes Kidney Yin and aggravates Heart Fire. One cup before noon.",
        "de": "Kaffee ist bitter-wärmend. Im Übermaß erschöpft er Nieren-Yin und verstärkt Herz-Feuer. Eine Tasse vor dem Mittag.",
        "es": "El café es amargo-calentador. En exceso agota Yin del Riñón y agrava el Fuego del Corazón. Una taza antes del mediodía.",
        "ar": "القهوة مرة-دافئة. بكميات زائدة تستنفد يين الكلى وتزيد نار القلب. كوب واحد قبل الظهر.",
        "th": "กาแฟขม-อุ่น หากมากเกินไปทำลายอินไต เพิ่มไฟหัวใจ หนึ่งแก้วก่อนเที่ยง",
        "ms": "Kopi pahit-hangat. Berlebihan menghabiskan Yin Ginjal. Secawan sebelum tengah hari."
      }
    }
  },
  "healingCrisis": {
    "intro": {
      "zh": "调理过程中可能出现以下\"排病反应\"，属于正气驱邪外出的正常现象，不必惊慌：",
      "en": "During the initial phase of treatment, temporary aggravation of symptoms may occur. In TCM, this is known as a \"healing crisis\" (排病反应 / Pái Bìng Fǎn Yìng) — a sign that the body is actively expelling pathogenic factors.",
      "de": "Zu Beginn der Behandlung kann eine vorübergehende Verschlimmerung auftreten. In der TCM wird dies als \"Erstverschlimmerung\" bezeichnet — ein Zeichen, dass der Körper krankmachende Faktoren ausleitet.",
      "es": "Durante la fase inicial del tratamiento puede ocurrir un agravamiento temporal. En la MTC se conoce como \"crisis curativa\" — señal de que el cuerpo expulsa factores patógenos.",
      "ar": "خلال المرحلة الأولى من العلاج قد يحدث تفاقم مؤقت. في الطب الصيني يُعرف بـ\"أزمة الشفاء\" — علامة على طرد العوامل المرضية.",
      "th": "ในช่วงแรกของการรักษาอาจมีอาการทรุดชั่วคราว ในแพทย์แผนจีนเรียกว่า \"ปฏิกิริยาการบำบัด\" — สัญญาณการขับปัจจัยก่อโรค",
      "ms": "Semasa fasa rawatan awal, pemburukan gejala sementara mungkin berlaku. Dalam perubatan Cina, ini dikenali sebagai \"krisis penyembuhan\" — tanda badan mengusir patogen."
    },
    "duration": {
      "zh": "排病反应通常持续3-7天后自行缓解，随后症状明显改善。",
      "en": "These reactions typically resolve within 3–7 days, followed by noticeable improvement.",
      "de": "Diese Reaktionen klingen in 3–7 Tagen ab, gefolgt von spürbarer Besserung.",
      "es": "Estas reacciones se resuelven en 3–7 días, seguidas de mejoría notable.",
      "ar": "تُحل هذه التفاعلات خلال 3-7 أيام، يليها تحسن ملحوظ.",
      "th": "ปฏิกิริยาเหล่านี้หายใน 3-7 วัน ตามด้วยอาการดีขึ้น",
      "ms": "Tindak balas ini sembuh dalam 3–7 hari, diikuti peningkatan ketara."
    },
    "redlineTitle": {
      "zh": "出现以下情况应立即停用并就医：",
      "en": "🚨 Red Line — Seek Immediate Medical Attention",
      "de": "🚨 Red Line — Sofort ärztliche Hilfe suchen",
      "es": "🚨 Línea Roja — Atención Médica Inmediata",
      "ar": "🚨 الخط الأحمر — اطلب الرعاية فوراً",
      "th": "🚨 เส้นแดง — พบแพทย์ทันที",
      "ms": "🚨 Garis Merah — Rawatan Segera"
    },
    "redlineText": {
      "zh": "剧烈腹痛、大量出血不止、高热不退(>38.5°C)、严重皮疹伴呼吸困难。这些不是排病反应，请立即就医。",
      "en": "Severe abdominal pain, excessively heavy bleeding (soaking a pad within 1 hour), high fever (>38.5°C / 101.3°F), severe rash with difficulty breathing. Discontinue all interventions immediately.",
      "de": "Starke Bauchschmerzen, übermäßig starke Blutungen, hohes Fieber (>38,5°C), schwerer Hautausschlag mit Atemnot. Brechen Sie alle Maßnahmen sofort ab.",
      "es": "Dolor abdominal severo, sangrado excesivo, fiebre alta (>38,5°C), erupción severa con dificultad respiratoria. Suspender todas las intervenciones.",
      "ar": "ألم بطني شديد، نزيف غزير، حمى عالية (>38.5°C)، طفح مع صعوبة تنفس. أوقف جميع التدخلات.",
      "th": "ปวดท้องรุนแรง เลือดออกมาก ไข้สูง (>38.5°C) ผื่นพร้อมหายใจลำบาก หยุดทั้งหมดทันที",
      "ms": "Sakit perut teruk, pendarahan berat, demam tinggi (>38.5°C), ruam dengan kesukaran bernafas. Hentikan serta-merta."
    }
  },
  "footer": {
    "brand": {
      "zh": "云非子｜舌鉴 · AI PRO+ 深度报告",
      "en": "YunFeiZi | AncientTongue.AI",
      "de": "YunFeiZi | AncientTongue.AI",
      "es": "YunFeiZi | AncientTongue.AI",
      "ar": "YunFeiZi | AncientTongue.AI",
      "th": "YunFeiZi | AncientTongue.AI",
      "ms": "YunFeiZi | AncientTongue.AI"
    },
    "product": {
      "zh": "AI PRO+ 深度分析报告",
      "en": "AI PRO+ Deep Analysis Report",
      "de": "KI PRO+ Tiefenanalysebericht",
      "es": "Informe de Análisis Profundo AI PRO+",
      "ar": "تقرير التحليل العميق AI PRO+",
      "th": "รายงานวิเคราะห์เชิงลึก AI PRO+",
      "ms": "Laporan Analisis Mendalam AI PRO+"
    },
    "disclaimer": {
      "zh": "本报告由AI系统生成，仅供中医文化学习与养生参考。不可替代临床诊疗，具体用药请遵医嘱。舌象分析基于中医舌诊理论，不代表现代医学诊断。个体差异可能导致不同的调理反应。",
      "en": "This report is AI-generated for educational and wellness reference purposes only. It does not constitute medical advice, diagnosis, or treatment. Interpretations are based on traditional Chinese medicine pattern differentiation theory and should not replace clinical evaluation by a licensed healthcare professional. Individual results may vary.",
      "de": "Dieser Bericht wurde von einer KI erstellt und dient ausschließlich Bildungs- und Wellnesszwecken. Er stellt keine medizinische Beratung dar. Die Interpretationen basieren auf der TCM-Syndrom-Differenzierungstheorie und ersetzen keine klinische Bewertung. Individuelle Ergebnisse können abweichen.",
      "es": "Este informe es generado por IA solo con fines educativos. No constituye consejo médico. Las interpretaciones se basan en la teoría de diferenciación de patrones de la MTC y no deben reemplazar la evaluación clínica. Los resultados individuales pueden variar.",
      "ar": "هذا التقرير مُنشأ بواسطة الذكاء الاصطناعي لأغراض تعليمية فقط. لا يشكل نصيحة طبية. التفسيرات تستند إلى نظرية التمييز بين الأنماط في الطب الصيني التقليدي. قد تختلف النتائج الفردية.",
      "th": "รายงานนี้สร้างโดย AI เพื่อการศึกษาเท่านั้น ไม่ถือเป็นคำแนะนำทางการแพทย์ การตีความอิงตามทฤษฎีการแพทย์แผนจีน ไม่ควรทดแทนการประเมินทางคลินิก ผลลัพธ์อาจแตกต่างกัน",
      "ms": "Laporan ini dijana oleh AI untuk tujuan pendidikan sahaja. Bukan nasihat perubatan. Tafsiran berdasarkan teori pembezaan corak perubatan Cina tradisional. Hasil individu mungkin berbeza."
    },
    "company": {
      "zh": "舌鉴人工智能科技（海南）有限公司",
      "en": "AncientTongue AI Technology (Hainan) Co., Ltd.",
      "de": "AncientTongue AI Technology (Hainan) Co., Ltd.",
      "es": "AncientTongue AI Technology (Hainan) Co., Ltd.",
      "ar": "AncientTongue AI Technology (Hainan) Co., Ltd.",
      "th": "AncientTongue AI Technology (Hainan) Co., Ltd.",
      "ms": "AncientTongue AI Technology (Hainan) Co., Ltd."
    },
    "contact": {
      "zh": "联系邮箱",
      "en": "Contact",
      "de": "Kontakt",
      "es": "Contacto",
      "ar": "اتصل بنا",
      "th": "ติดต่อ",
      "ms": "Hubungi"
    },
    "contactEmail": "zhangyunfei@shejianai.com.cn"
  },
  "common": {
    "followUpNote": {
      "zh": "建议每2周观察一次，调理3个月后复拍舌象对比。",
      "en": "Self-assess every 2 weeks. Submit new tongue photos at 3 months for comparative AI analysis.",
      "de": "Selbstbeurteilung alle 2 Wochen. Nach 3 Monaten neue Zungenfotos zur KI-Analyse einreichen.",
      "es": "Autoevaluación cada 2 semanas. Envíe nuevas fotos a los 3 meses.",
      "ar": "تقييم ذاتي كل أسبوعين. قدّم صور لسان جديدة عند 3 أشهر.",
      "th": "ประเมินทุก 2 สัปดาห์ ส่งรูปใหม่เมื่อ 3 เดือน",
      "ms": "Penilaian sendiri setiap 2 minggu. Hantar gambar baru pada 3 bulan."
    },
    "formulaSchool": {
      "zh": "学派：火神扶阳派 · 经方体系",
      "en": "School: Huoshen Fu Yang School · Classical Formula (Jing Fang) System",
      "de": "Schule: Huoshen Fu Yang Schule · Klassisches Rezept-System (Jing Fang)",
      "es": "Escuela Huoshen Fu Yang · Fórmulas Clásicas (Jing Fang)",
      "ar": "مدرسة هوو شين فو يانغ · الوصفات الكلاسيكية",
      "th": "สำนักหั่วเสินฝูหยาง · ตำรับโบราณ",
      "ms": "Aliran Huoshen Fu Yang · Formula Klasik (Jing Fang)"
    },
    "formulaDisclaimer": {
      "zh": "以上为AI基于舌象分析的经典方剂方向参考，不构成处方建议。具体用药需经中医师四诊合参后确定。",
      "en": "These formulas are AI-generated references only. They do not constitute a prescription. Clinical use requires assessment by a licensed practitioner.",
      "de": "Diese Rezepturen sind KI-Referenzen. Sie stellen kein Rezept dar. Klinische Anwendung erfordert Bewertung durch einen Praktiker.",
      "es": "Fórmulas generadas por IA como referencia. No son prescripción. Uso clínico requiere evaluación profesional.",
      "ar": "وصفات مُنشأة بواسطة AI كمرجع. ليست وصفة طبية. الاستخدام السريري يتطلب تقييم مختص.",
      "th": "ตำรับอ้างอิงจาก AI ไม่ใช่ใบสั่งยา การใช้ต้องประเมินโดยผู้ประกอบวิชาชีพ",
      "ms": "Formula rujukan AI. Bukan preskripsi. Penggunaan klinikal memerlukan penilaian pengamal berlesen."
    },
    "redFlagNote": {
      "zh": "以上为肝郁血瘀体质常见的器质性病变高危部位，建议定期超声检查。AI不作诊断，具体请遵医嘱。",
      "en": "Common sites where Liver-Constitution / Blood-Stasis tends to manifest. Early screening recommended for prevention.",
      "de": "Häufige Lokalisationen des Leber-Blut-Stase-Musters. Frühscreening zur Prävention empfohlen.",
      "es": "Sitios comunes donde tiende a manifestarse el patrón Hígado/Estasis. Cribado temprano recomendado.",
      "ar": "مواقع شائعة لظهور نمط الكبد/ركود الدم. يُوصى بالفحص المبكر.",
      "th": "ตำแหน่งที่พบบ่อยของกลุ่มอาการตับ/เลือดค้าง แนะนำคัดกรอง早期",
      "ms": "Tapak biasa Corak Hati/Stasis Darah. Saringan awal disyorkan."
    },
    "tongueAbove": {
      "zh": "舌上",
      "en": "Tongue (Dorsal)",
      "de": "Zunge (Dorsal)",
      "es": "Lengua (Dorsal)",
      "ar": "اللسان (العلوي)",
      "th": "ลิ้น (บน)",
      "ms": "Lidah (Dorsal)"
    },
    "tongueBelow": {
      "zh": "舌下",
      "en": "Sublingual (Ventral)",
      "de": "Sublingual (Ventral)",
      "es": "Sublingual (Ventral)",
      "ar": "تحت اللسان",
      "th": "ใต้ลิ้น",
      "ms": "Sublingual (Ventral)"
    },
    "crossConsistent": {
      "zh": "互证一致",
      "en": "Cross-Validated",
      "de": "Kreuzvalidiert",
      "es": "Validado Cruzado",
      "ar": "تم التحقق المتبادل",
      "th": "ตรวจสอบไขว้สอดคล้อง",
      "ms": "Disahkan Silang"
    },
    "screeningRecommended": {
      "zh": "建议排查",
      "en": "Screening Recommended",
      "de": "Screening empfohlen",
      "es": "Screening Recomendado",
      "ar": "يُنصح بالفحص",
      "th": "แนะนำให้คัดกรอง",
      "ms": "Saringan Disyorkan"
    },
    "predictionLabel": {
      "zh": "预判",
      "en": "PREDICTION",
      "de": "VORHERSAGE",
      "es": "PREDICCIÓN",
      "ar": "توقع",
      "th": "คาดการณ์",
      "ms": "RAMALAN"
    },
    "recipeLabel": {
      "zh": "食谱",
      "en": "RECIPE",
      "de": "REZEPT",
      "es": "RECETA",
      "ar": "وصفة",
      "th": "สูตร",
      "ms": "RESIPI"
    },
    "indicatorLabel": {
      "zh": "指标",
      "en": "INDICATOR",
      "de": "INDIKATOR",
      "es": "INDICADOR",
      "ar": "مؤشر",
      "th": "ตัวบ่งชี้",
      "ms": "PENUNJUK"
    },
    "targetLabel": {
      "zh": "目标",
      "en": "Target",
      "de": "Ziel",
      "es": "Objetivo",
      "ar": "الهدف",
      "th": "เป้าหมาย",
      "ms": "Sasaran"
    },
    "mechanism": {
      "zh": "机理",
      "en": "Mechanism",
      "de": "Mechanismus",
      "es": "Mecanismo",
      "ar": "الآلية",
      "th": "กลไก",
      "ms": "Mekanisme"
    },
    "suggested": {
      "zh": "建议关注",
      "en": "Suggested",
      "de": "Empfohlen",
      "es": "Sugerido",
      "ar": "مقترح",
      "th": "แนะนำ",
      "ms": "Cadangan"
    },
    "sixStagesLabel": {
      "zh": "六经",
      "en": "Six Stages",
      "de": "Sechs Stufen",
      "es": "Seis Etapas",
      "ar": "المراحل الست",
      "th": "หกชั้น",
      "ms": "Enam Peringkat"
    },
    "patternLabel": {
      "zh": "证型",
      "en": "Pattern",
      "de": "Syndrom",
      "es": "Patrón",
      "ar": "النمط",
      "th": "กลุ่มอาการ",
      "ms": "Corak"
    },
    "ingredients": {
      "zh": "材料",
      "en": "Ingredients",
      "de": "Zutaten",
      "es": "Ingredientes",
      "ar": "المكونات",
      "th": "ส่วนผสม",
      "ms": "Bahan"
    },
    "preparation": {
      "zh": "做法",
      "en": "Preparation",
      "de": "Zubereitung",
      "es": "Preparación",
      "ar": "التحضير",
      "th": "วิธีทำ",
      "ms": "Penyediaan"
    },
    "effect": {
      "zh": "功效",
      "en": "Effect",
      "de": "Wirkung",
      "es": "Efecto",
      "ar": "التأثير",
      "th": "สรรพคุณ",
      "ms": "Kesan"
    },
    "direction": {
      "zh": "方向",
      "en": "Direction",
      "de": "Richtung",
      "es": "Dirección",
      "ar": "الاتجاه",
      "th": "ทิศทาง",
      "ms": "Arah"
    },
    "indication": {
      "zh": "适用",
      "en": "Indication",
      "de": "Indikation",
      "es": "Indicación",
      "ar": "الدلالة",
      "th": "ข้อบ่งใช้",
      "ms": "Petunjuk"
    },
    "source": {
      "zh": "来源",
      "en": "Source",
      "de": "Quelle",
      "es": "Fuente",
      "ar": "المصدر",
      "th": "ที่มา",
      "ms": "Sumber"
    },
    "classification": {
      "zh": "分类",
      "en": "Classification",
      "de": "Klassifikation",
      "es": "Clasificación",
      "ar": "التصنيف",
      "th": "การจำแนก",
      "ms": "Klasifikasi"
    },
    "observation": {
      "zh": "观察",
      "en": "Observation",
      "de": "Beobachtung",
      "es": "Observación",
      "ar": "الملاحظة",
      "th": "การสังเกต",
      "ms": "Pemerhatian"
    },
    "interpretation": {
      "zh": "解读",
      "en": "Interpretation",
      "de": "Interpretation",
      "es": "Interpretación",
      "ar": "التفسير",
      "th": "การตีความ",
      "ms": "Tafsiran"
    },
    "analysis": {
      "zh": "辨析",
      "en": "Analysis",
      "de": "Analyse",
      "es": "Análisis",
      "ar": "التحليل",
      "th": "การวิเคราะห์",
      "ms": "Analisis"
    },
    "presentation": {
      "zh": "具体表现",
      "en": "Presentation",
      "de": "Erscheinung",
      "es": "Presentación",
      "ar": "المظاهر",
      "th": "ลักษณะ",
      "ms": "Persembahan"
    },
    "significance": {
      "zh": "提示",
      "en": "Significance",
      "de": "Bedeutung",
      "es": "Significado",
      "ar": "الدلالة",
      "th": "ความหมาย",
      "ms": "Keterangan"
    },
    "pattern": {
      "zh": "证候",
      "en": "Pattern",
      "de": "Muster",
      "es": "Patrón",
      "ar": "النمط",
      "th": "กลุ่มอาการ",
      "ms": "Corak"
    }
  }
};

/**
 * Helper: Get translation by dot-notation path
 * @param {string} lang - Language code (zh/en/de/es/ar/th/ms)
 * @param {string} path - Dot-notation path (e.g., 'sections.tongueBody.title')
 * @param {string} fallbackLang - Fallback language, default 'en'
 * @returns {string} Translated text
 */
export function t(lang, path, fallbackLang = 'en') {
  const keys = path.split('.');
  let result = translations;
  for (const key of keys) {
    if (result && typeof result === 'object' && key in result) {
      result = result[key];
    } else {
      return `[${path}]`;
    }
  }
  if (typeof result === 'object' && result !== null) {
    return (result[lang] || result[fallbackLang] || '').toString();
  }
  return String(result || '');
}

/**
 * Get text direction for a language
 * @param {string} lang 
 * @returns {'ltr'|'rtl'}
 */
export function getDirection(lang) {
  return translations.meta?.direction?.[lang] || 'ltr';
}

/**
 * Get all supported languages
 * @returns {string[]}
 */
export function getSupportedLanguages() {
  return translations.meta?.languages || ['zh', 'en', 'de', 'es', 'ar', 'th', 'ms'];
}

export default translations;
